site_name: HPLC Club
site_description: HPLC 技术交流社区
repo_url: https://github.com/Tangrenbin/hplc-club
repo_name: Tangrenbin/hplc-club
docs_dir: md_doc
site_dir: site
site_url: https://hplc-club.990124.xyz/

theme:
  name: material
  language: zh
  icon:
    logo: material/book-open-page-variant
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra_css:
  - assets/stylesheets/extra.css
